### ISSUE TITLE
drv_common.c是不是改错了啊

### ISSUE THREAD

**Issue by diskwu** [RT-Thread-Studio/sdk-csp-stm32f4#3]
drv_common.c前一次把MSH_CMD_EXPORT_ALIAS改对了（03916b55de2842f276dca8a5cdd3520187ec2f46），
下一次更新却又删了啊（6106f7bf2a9e17e0e0ee23e5adf66396a2a424e3）。
4.0.4之后改掉了FINSH，不能用旧的了。否则影响reboot功能。

**Comment by Guozhanxin** [comment]
0.2.3的版本修正过来了
